/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import java.util.Scanner;
import org.example.Student;
import org.example.StudentService;

public class App {
    public static void main(String[] args) {
        StudentService service = new StudentService();
        Scanner scanner = new Scanner(System.in);
        int choice;

        do {
            System.out.println("\n--- Student Management System ---");
            System.out.println("1. Add Student");
            System.out.println("2. View Students");
            System.out.println("3. Search Student");
            System.out.println("4. Delete Student");
            System.out.println("0. Exit");
            System.out.print("Enter your choice: ");
            choice = scanner.nextInt();

            switch (choice) {
                case 1 -> {
                    System.out.print("Enter ID: ");
                    int id = scanner.nextInt();
                    System.out.print("Enter Name: ");
                    String name = scanner.next();
                    System.out.print("Enter Age: ");
                    int age = scanner.nextInt();
                    service.addStudent(new Student(id, name, age));
                    System.out.println("Student Added!");
                }
                case 2 -> {
                    service.getAllStudents().forEach(System.out::println);
                }
                case 3 -> {
                    System.out.print("Enter ID to search: ");
                    int id = scanner.nextInt();
                    service.findStudentById(id).ifPresentOrElse(
                        System.out::println,
                        () -> System.out.println("Student Not Found.")
                    );
                }
                case 4 -> {
                    System.out.print("Enter ID to delete: ");
                    int id = scanner.nextInt();
                    if (service.deleteStudent(id)) {
                        System.out.println("Student Deleted.");
                    } else {
                        System.out.println("Student Not Found.");
                    }
                }
                case 0 -> System.out.println("Exiting...");
                default -> System.out.println("Invalid Choice!");
            }
        } while (choice != 0);

        scanner.close();
    }
}

