/*
 * This source file was generated by the Gradle 'init' task
 */
// package org.example;

// import org.junit.Test;
// import static org.junit.Assert.*;

// public class AppTest {
//     @Test public void appHasAGreeting() {
//         App classUnderTest = new App();
//         assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//     }
// }
package org.example;


import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testAddAndFindStudent() {
        StudentService service = new StudentService();
        Student s = new Student(1, "John", 20);
        service.addStudent(s);
        assertTrue(service.findStudentById(1).isPresent());
    }

    @Test
    public void testDeleteStudent() {
        StudentService service = new StudentService();
        service.addStudent(new Student(2, "Alice", 22));
        assertTrue(service.deleteStudent(2));
        assertFalse(service.findStudentById(2).isPresent());
    }
}
